name = "SpmImages"
uuid = "a5d333f8-9588-4c9f-ac4d-4583361e1fcb"
authors = ["Alex Riss"]
keywords = ["SPM", "STM", "AFM", "scanning probe microscopy", "scanning tunneling microscopy", "atomic force microscopy", "images", "image analysis"]
license = "GPLv3"
desc = "Read and display SPM (scanning probe microscopy) images"
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
