name = "SpmImages"
uuid = "a5d333f8-9588-4c9f-ac4d-4583361e1fcb"
keywords = ["SPM", "STM", "AFM", "scanning probe microscopy", "scanning tunneling microscopy", "atomic force microscopy", "images", "image analysis"]
license = "GPLv3"
desc = "Read and display SPM (scanning probe microscopy) images"
authors = ["Alex Riss"]
version = "0.4.0"

[deps]
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
CoordinateTransformations = "^0.6"
DataStructures = "^0.18"
ImageFiltering = "^0.7"
ImageTransformations = "^0.10"
NetCDF = "=0.11.7"
julia = "^1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
