name = "SpmImages"
uuid = "a5d333f8-9588-4c9f-ac4d-4583361e1fcb"
keywords = ["SPM", "STM", "AFM", "scanning probe microscopy", "scanning tunneling microscopy", "atomic force microscopy", "images", "image analysis"]
license = "GPLv3"
desc = "Read and display SPM (scanning probe microscopy) images"
authors = ["Alex Riss"]
version = "0.2.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
DataStructures = "^0.18"
Plots = "^1.25"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
